# Generated by Django 4.0 on 2021-12-19 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geolocation',
            name='ip',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
